-- Generated from generator/demo_specs/aws-philippines-retail-personalization.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-retail-personalization
-- This is the schema that is actually deployed for PH_RETAIL_PERSONALIZATION.

-- Alerts fire on the bottom tail of Recommendation CTR
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_RECOMMENDATION_CTR) AS T
  FROM RAW.BROWSE_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_RECOMMENDATION_CTR <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_RECOMMENDATION_CTR), 2) AS AVG_RECOMMENDATION_CTR,
  ROUND(AVG(f.KPI_A_B_TESTS_ACTIVE), 2) AS AVG_A_B_TESTS_ACTIVE,
  ROUND(AVG(f.KPI_MODELS_DEPLOYED), 2) AS AVG_MODELS_DEPLOYED,
  ROUND(AVG(f.KPI_REVENUE_LIFT_AVG), 2) AS AVG_REVENUE_LIFT,
  ROUND(AVG(f.KPI_ENGAGEMENT_LIFT), 2) AS AVG_ENGAGEMENT_LIFT,
  ROUND(AVG(f.KPI_TEST_VELOCITY), 2) AS AVG_TEST_VELOCITY
FROM RAW.BROWSE_EVENTS f
JOIN RAW.PRODUCT_CATALOG e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_RECOMMENDATION_CTR), 2) AS AVG_RECOMMENDATION_CTR,
  ROUND(AVG(f.KPI_A_B_TESTS_ACTIVE), 2) AS AVG_A_B_TESTS_ACTIVE,
  ROUND(AVG(f.KPI_MODELS_DEPLOYED), 2) AS AVG_MODELS_DEPLOYED,
  ROUND(AVG(f.KPI_REVENUE_LIFT_AVG), 2) AS AVG_REVENUE_LIFT,
  ROUND(AVG(f.KPI_ENGAGEMENT_LIFT), 2) AS AVG_ENGAGEMENT_LIFT,
  ROUND(AVG(f.KPI_TEST_VELOCITY), 2) AS AVG_TEST_VELOCITY
FROM RAW.BROWSE_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_RECOMMENDATION_CTR) AS KPI_RECOMMENDATION_CTR, AVG(KPI_A_B_TESTS_ACTIVE) AS KPI_A_B_TESTS_ACTIVE, AVG(KPI_MODELS_DEPLOYED) AS KPI_MODELS_DEPLOYED, AVG(KPI_REVENUE_LIFT_AVG) AS KPI_REVENUE_LIFT_AVG, AVG(KPI_ENGAGEMENT_LIFT) AS KPI_ENGAGEMENT_LIFT, AVG(KPI_TEST_VELOCITY) AS KPI_TEST_VELOCITY FROM RAW.BROWSE_EVENTS),
     en AS (SELECT SUM(KPI_PERSONALIZED_REVENUE) AS KPI_PERSONALIZED_REVENUE FROM RAW.PRODUCT_CATALOG)
  SELECT 1 AS SORT_ORDER, 'Recommendation CTR' AS TITLE, KPI_RECOMMENDATION_CTR AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RECOMMENDATION_CTR), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Personalized Revenue' AS TITLE, KPI_PERSONALIZED_REVENUE AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_PERSONALIZED_REVENUE) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'A/B Tests Active' AS TITLE, KPI_A_B_TESTS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_A_B_TESTS_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Models Deployed' AS TITLE, KPI_MODELS_DEPLOYED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MODELS_DEPLOYED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Revenue Lift (Avg)' AS TITLE, KPI_REVENUE_LIFT_AVG AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_REVENUE_LIFT_AVG)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Engagement Lift' AS TITLE, KPI_ENGAGEMENT_LIFT AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_ENGAGEMENT_LIFT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Test Velocity' AS TITLE, KPI_TEST_VELOCITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TEST_VELOCITY)) AS DECIMAL(38,0))) || '/week' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
