-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Consumer Insights & Personalization Engine
-- ============================================================================
USE DATABASE CONSUMER_INSIGHTS;
USE SCHEMA ML;

-- ML.CLASSIFICATION: PURCHASE_INTENT_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.PURCHASE_INTENT_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CUSTOMER_360'),
  TARGET_COLNAME => 'WILL_PURCHASE_7D'
);

-- ML.CLASSIFICATION: CHURN_RISK_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CHURN_RISK_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CUSTOMER_360'),
  TARGET_COLNAME => 'WILL_CHURN_30D'
);

