-- ============================================================================
-- 99_RESET.SQL — Reset Consumer Insights & Personalization Engine to clean demo state
-- ============================================================================
USE DATABASE CONSUMER_INSIGHTS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_BEHAVIOR SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_CUSTOMERS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_OFFERS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CUSTOMER_360 REFRESH;
ALTER DYNAMIC TABLE CURATED.SEGMENT_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.PRODUCT_AFFINITY REFRESH;
ALTER DYNAMIC TABLE CURATED.NEXT_BEST_OFFER REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM CONSUMER_INSIGHTS.RAW.BROWSE_EVENTS → 45000000
-- SELECT COUNT(*) FROM CONSUMER_INSIGHTS.RAW.CUSTOMERS → 2800000
-- SELECT COUNT(*) FROM CONSUMER_INSIGHTS.CURATED.CUSTOMER_360 WHERE CHURN_RISK_SCORE > 0.8 → ~342000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_OFFERS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_CUSTOMERS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_BEHAVIOR RESUME;
